index:
    path: /chat/slack/messages
    controller: slub.infrastructure.chat.slack.slub_bot_action::executeAction
    methods: [POST]

vcs_github_new_review:
    path: /vcs/github/new_review
    controller: slub.infrastructure.vcs.github.new_review_action:executeAction
    methods: [POST]
