parameters:
    SUPPORTED_REPOSITORIES: "akeneo/pim-community-dev,SamirBoulil/slub"
    SUPPORTED_CHANNELS: "squad-raccoons,general"
    GITHUB_WEBHOOK_SECRET: "my_secret"

services:
    # default configuration for services in *this* file
    _defaults:
        public: true

    helpers.event_spy:
        class: Tests\Acceptance\helpers\EventsSpy
        tags:
            - { name: kernel.event_subscriber }
        public: true

    slub.infrastructure.chat.slack.slack_client:
        class: Tests\Acceptance\helpers\ChatClientSpy

    slub.infrastructure.query.get_channel_information:
        class: Slub\Infrastructure\Persistence\InMemory\Query\InMemoryGetChannelInformation
        arguments:
            - "%env(SUPPORTED_CHANNELS)%"
