parameters:
    slub.repositories:
        - "akeneo/pim-community-dev"
    slub.channels:
        - "squad-raccoons"
        - "squad-chipmunks"

services:
    # default configuration for services in *this* file
    _defaults:
        public: false

    helpers.event_spy:
        class: Tests\Acceptance\helpers\EventsSpy
        tags:
            - { name: kernel.event_subscriber }
        public: true

