parameters:
    slub.repositories:
        - "akeneo/pim-community-dev"
        - "SamirBoulil/slub"
    slub.channels:
        - "squad-raccoons"
        - "general"

services:
    # default configuration for services in *this* file
    _defaults:
        public: true

    helpers.event_spy:
        class: Tests\Acceptance\helpers\EventsSpy
        tags:
            - { name: kernel.event_subscriber }
        public: true

    slub.infrastructure.chat.slack.slack_client:
        class: Tests\Acceptance\helpers\ChatClientSpy

    slub.infrastructure.query.get_channel_information:
        class: Slub\Infrastructure\Persistence\InMemory\Query\InMemoryGetChannelInformation
        arguments:
            - "%slub.channels%"

    slub.infrastructure.persistence.pr_repository:
        class: Slub\Infrastructure\Persistence\FileBased\Repository\FileBasedPRRepository
        arguments:
            - "@event_dispatcher"
            - "%slub.infrastructure.persistence.file_database%"

    slub.infrastructure.persistence.get_message_ids_for_pr:
        class: Slub\Infrastructure\Persistence\FileBased\Query\FileBasedGetMessageIdsForPR
        arguments:
            - "%slub.infrastructure.persistence.file_database%"
